name: release

on:
  push:
    branches:
      - 'main'
      - 'release-*'

env:
  VERSION: 0.1.0

jobs:
  tag-release:
    runs-on: [arc-amd64-runner-set]
    container: "ubuntu:latest"
    steps:
      - name: Create tag
        if: github.ref_name == 'main'
        uses: westonrobot-dev/github-tag-action@v6.1
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.VERSION }}
          release_branches: "master,main,v1-branch"
          pre_release_branches: "prerelease"
      - name: Create Github Release
        if: github.ref_name == 'main'
        uses: westonrobot-dev/workflow-dispatch@v1.2.2
        with:
          workflow: release-github.yml
          ref: ${{ steps.tag_version.outputs.new_tag }}